stages:
    - test

image: registry.gitlab.com/torese/docker-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'

.run_playbook:
    allow_failure: true
    script:

        - ansible all -m ping -i $inventory

deploy_dev:
    extends: .run_playbook
    variables:
        inventory: k8s-nodes.yaml
    stage: test